### ISSUE TITLE
--model_name_or_path: error

### ISSUE THREAD

**Issue by nuraliyevaassel** [Mayer123/HyKAS#1]
Hello 
when I run 
CUDA_VISIBLE_DEVICES=0 python run_csqa.py --data_dir data/ --model_type roberta-ocn-inj --model_name_or_path 
roberta-large --task_name csqa-inj --cache_dir downloaded_models --max_seq_length 80 --do_train --do_eval 
--evaluate_during_training --per_gpu_train_batch_size 4 --gradient_accumulation_steps 8 --learning_rate 1e-5 
--num_train_epochs 8 --warmup_steps 150 --output_dir workspace/hykas

I get a error: argument --model_name_or_path: expected one argument
zsh: command not found: roberta-large

How can I fix it?

**Comment by Mayer123** [comment]
Hello, I think you can either add an escape character after the end of every line, e.g. "--model_name_or_path \ " or copy-paste every line of command individually to your terminal (without newline) to run it. Basically, we want the bash to interpret this as one command instead of several.
